name: Build, Push, and Deploy Telegram Bot

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: education
  DOCKER_IMAGE_TAG: latest
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USERNAME: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

      - name: Deploy Docker image and Redis to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Redis-ni ishga tushirish (agar ishlamayotgan bo'lsa)
            docker ps | grep redis || docker run -d --name redis \
              -e REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} \
              -p 6379:6379 redis:latest --requirepass ${{ env.REDIS_PASSWORD }}

            # Eski botni to‘xtatish va o‘chirish
            docker stop education || true
            docker rm education || true
            docker image rm $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG || true

            # Yangi botni Redis bilan birga ishga tushirish
            docker run -d --name education \
              -e TELEGRAM_TOKEN=${{ env.TELEGRAM_TOKEN }} \
              -e POSTGRES_HOST=${{ env.DATABASE_HOST }} \
              -e POSTGRES_USER=${{ env.DATABASE_USER }} \
              -e POSTGRES_PASSWORD=${{ env.DATABASE_PASSWORD }} \
              -e REDIS_HOST=${{ env.REDIS_HOST }} \
              -e REDIS_PORT=${{ env.REDIS_PORT }} \
              -e REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} \
              $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
